device: cuda

dataset_name: mayo2016-144view

train_X_folder_path: /home_data/home/yaoql2023/mayo2016/processed/train/144-view
train_y_folder_path: /home_data/home/yaoql2023/mayo2016/processed/train/full_3mm 

test_X_folder_path: /home_data/home/yaoql2023/mayo2016/processed/test/144-view
test_y_folder_path: /home_data/home/yaoql2023/mayo2016/processed/test/full_3mm 

use_wandb: False
wandb_project: RobustMLProject

ckpt_save_interval: 5
log_print_interval: 1

