lr: 5e-4
weight_decay: 1e-5
batch_size: 4
num_workers: 8

lambda1: 1
lambda2: 1
epsilon: 0.0001 

epoch: 100
data_range: 1
ckpt_save_folder: /data/DATA/yaoqiulei/RobustMLProject/FBPConvNetAdv/ckpt
log_save_folder: /data/DATA/yaoqiulei/RobustMLProject/FBPConvNetAdv/log

# 这个version代表模型的version，每一次修改模型都需要修改version
version: FBPConvAdv-1